# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.10.8 on 2017-09-27 08:39
=======
# Generated by Django 1.10.7 on 2017-09-27 10:03
>>>>>>> 847442984f916e30ea3417ba461349dedd6b1cd1
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('consumers', '0001_initial'),
=======
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consumers', '__first__'),
>>>>>>> 847442984f916e30ea3417ba461349dedd6b1cd1
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('healthier_id', models.CharField(default='provider_l9qqxx2ehch1hlm7c08v', max_length=30)),
=======
                ('healthier_id', models.CharField(default='provider_k89sgc6mt8el4r3n6k3b', max_length=30)),
                ('user_details_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consumer_details', to=settings.AUTH_USER_MODEL)),
>>>>>>> 847442984f916e30ea3417ba461349dedd6b1cd1
            ],
        ),
        migrations.CreateModel(
            name='ProviderRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(blank=True, max_length=200, null=True)),
                ('dislikes', models.IntegerField(blank=True, default=0)),
                ('likes', models.IntegerField(blank=True, default=0)),
                ('provider', models.OneToOneField(db_column='provider_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provider_rating', to='providers.Provider')),
                ('rated_by', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_rating', to='consumers.Consumer')),
            ],
        ),
    ]
