# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-12 13:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consumers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('logo', models.ImageField(upload_to='uploads/images/providers/')),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=200)),
                ('website', models.URLField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provider_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProviderRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(blank=True, max_length=200, null=True)),
                ('dislikes', models.IntegerField(blank=True, default=0)),
                ('likes', models.IntegerField(blank=True, default=0)),
                ('healthier_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_rating', to='consumers.Consumer')),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provider_rating', to='providers.Provider')),
            ],
        ),
    ]
