# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-26 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='healthier_id',
            field=models.CharField(default='provider_3t35c1ise37egh2ihpvd', max_length=30),
        ),
    ]
