# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-18 07:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import healthier.providers.managers


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='provider',
            managers=[
                ('objects', healthier.providers.managers.ProviderManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='provider',
            name='user',
        ),
        migrations.AddField(
            model_name='provider',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Joined'),
        ),
        migrations.AddField(
            model_name='provider',
            name='email',
            field=models.EmailField(default='', error_messages={'unique': 'Provider Email'}, max_length=255, unique=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='provider',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this hospital belongs to. An hospital will get all permissions granted to each of their groups.', related_name='hospital_set', related_query_name='hospital', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='provider',
            name='healthier_ID',
            field=models.CharField(default='providers_fp0caubig4uqz0ifqjbi', max_length=30),
        ),
        migrations.AddField(
            model_name='provider',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='provider',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Admin'),
        ),
        migrations.AddField(
            model_name='provider',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AddField(
            model_name='provider',
            name='password',
            field=models.CharField(default='', max_length=128, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Provider Name'),
        ),
    ]
