# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-18 08:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_auto_20170918_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='provider',
            name='healthier_ID',
            field=models.CharField(default='providers_mkvdizp0onm0j4cbwgru', max_length=30),
        ),
        migrations.AlterField(
            model_name='provider',
            name='password',
            field=models.CharField(default='', error_messages={'required': 'This field is required'}, max_length=128, verbose_name='Password'),
        ),
    ]
