# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-26 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0003_auto_20170925_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='healthier_id',
            field=models.CharField(default='provider_pp2uvi2ohjaj35a3n1o7', max_length=30),
        ),
    ]
