# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-18 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0003_auto_20170918_0834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='groups',
        ),
        migrations.AlterField(
            model_name='provider',
            name='healthier_ID',
            field=models.CharField(default='provider_4xzu6ysdv4xnxifd441b', max_length=30),
        ),
    ]
