# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-20 11:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0004_auto_20170918_1604'),
        ('providers', '0004_auto_20170918_1300'),
    ]

    operations = [
    ]
