# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-20 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0005_merge_20170920_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='healthier_ID',
            field=models.CharField(default='provider_xq4yuupw2kwr9nn3hwdj', max_length=30),
        ),
    ]
