# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-26 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0005_auto_20170926_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='healthier_id',
            field=models.CharField(default='provider_f0nqf9k76393wv45k4l6', max_length=30),
        ),
    ]
