# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-24 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0010_auto_20170924_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='services_offered',
            field=jsonfield.fields.JSONField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='provider',
            name='healthier_id',
            field=models.CharField(default='provider_cy7cu3l1ckyj6tlpg9x7', max_length=30),
        ),
    ]
