# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-25 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basehealthierservice',
            name='service_id',
            field=models.CharField(default='service_r4h91l0axcej5b5iaxk2', max_length=200),
        ),
        migrations.AlterField(
            model_name='orderedservice',
            name='order_id',
            field=models.CharField(default='order_43uhtyoleh4k4qlsk5fs', max_length=200),
        ),
    ]
