# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-26 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20170925_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basehealthierservice',
            name='service_id',
            field=models.CharField(default='service_qgbre09kn3blwtgrvj3j', max_length=200),
        ),
        migrations.AlterField(
            model_name='orderedservice',
            name='order_id',
            field=models.CharField(default='order_miduw4xd3xzq0n57ecd4', max_length=200),
        ),
    ]
