# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-24 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20170924_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basehealthierservice',
            name='service_id',
            field=models.CharField(default='service_7rsz62k8irvce8onozkk', max_length=200),
        ),
        migrations.AlterField(
            model_name='orderedservice',
            name='order_id',
            field=models.CharField(default='order_7w90602lhlymu4g91y0y', max_length=200),
        ),
    ]
