# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-26 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20170926_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basehealthierservice',
            name='service_id',
            field=models.CharField(default='service_1i88vlvfn38z7v70v7vc', max_length=200),
        ),
        migrations.AlterField(
            model_name='orderedservice',
            name='order_id',
            field=models.CharField(default='order_0a98891pl7o7g30rfs1x', max_length=200),
        ),
    ]
