# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-26 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20170926_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basehealthierservice',
            name='service_id',
            field=models.CharField(default='service_sn7u8otlhkxg76wyq3xm', max_length=200),
        ),
        migrations.AlterField(
            model_name='orderedservice',
            name='order_id',
            field=models.CharField(default='order_d1ptdjkzklf2h73eg6lu', max_length=200),
        ),
    ]
