# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-24 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20170924_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basehealthierservice',
            name='service_id',
            field=models.CharField(default='service_1a4cfzkj5bspowbg53eb', max_length=200),
        ),
        migrations.AlterField(
            model_name='orderedservice',
            name='order_id',
            field=models.CharField(default='order_a2nxdg2ipsrvvpqi515y', max_length=200),
        ),
    ]
