# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-24 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_auto_20170924_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basehealthierservice',
            name='service_id',
            field=models.CharField(default='service_jcreqphp0tdyphb81m7b', max_length=200),
        ),
        migrations.AlterField(
            model_name='orderedservice',
            name='order_id',
            field=models.CharField(default='order_09grw7np2b1v5c0pn2y5', max_length=200),
        ),
    ]
