# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-24 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_auto_20170924_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basehealthierservice',
            name='service_id',
            field=models.CharField(default='service_qbk8dw06tgmthc4ebq05', max_length=200),
        ),
        migrations.AlterField(
            model_name='orderedservice',
            name='order_id',
            field=models.CharField(default='order_rop2ah3u2lonbcaosdtj', max_length=200),
        ),
    ]
