# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-24 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_auto_20170924_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basehealthierservice',
            name='service_id',
            field=models.CharField(default='service_tnzad7t80rc3q0luu0x3', max_length=200),
        ),
        migrations.AlterField(
            model_name='orderedservice',
            name='order_id',
            field=models.CharField(default='order_pzxlupu7dnq4usofdt9g', max_length=200),
        ),
    ]
