# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-24 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_auto_20170924_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basehealthierservice',
            name='service_id',
            field=models.CharField(default='service_u0azeltzwzlb9d9secn1', max_length=200),
        ),
        migrations.AlterField(
            model_name='orderedservice',
            name='order_id',
            field=models.CharField(default='order_ina55zknt7lbdqwb4cxp', max_length=200),
        ),
    ]
