# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-24 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_auto_20170924_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basehealthierservice',
            name='service_id',
            field=models.CharField(default='service_0gdj26lwh2wtv0rxbb3g', max_length=200),
        ),
        migrations.AlterField(
            model_name='orderedservice',
            name='order_id',
            field=models.CharField(default='order_sym6ds07tbl0u4k22455', max_length=200),
        ),
    ]
