# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-25 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('healthier_id', models.CharField(default='consumer_hw4fkgzqzuiqzzru82z0', max_length=30)),
            ],
        ),
    ]
