# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.10.8 on 2017-09-27 08:39
=======
# Generated by Django 1.10.7 on 2017-09-27 10:03
>>>>>>> 847442984f916e30ea3417ba461349dedd6b1cd1
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('healthier_id', models.CharField(default='consumer_sk0nkvgppdmprbo573ih', max_length=30)),
=======
                ('healthier_id', models.CharField(default='consumer_x3mvx2zjxlrycci80n36', max_length=30)),
                ('user_details_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provider_details', to=settings.AUTH_USER_MODEL)),
>>>>>>> 847442984f916e30ea3417ba461349dedd6b1cd1
            ],
        ),
    ]
