# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-26 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0002_auto_20170926_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='healthier_id',
            field=models.CharField(default='consumer_mtx1qe9xfxsuu0u1m18e', max_length=30),
        ),
    ]
