# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-25 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0002_consumer_user_details_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='healthier_id',
            field=models.CharField(default='consumer_14zby50ikmmwl0oglh2s', max_length=30),
        ),
    ]
