# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-26 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0003_auto_20170925_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='healthier_id',
            field=models.CharField(default='consumer_yqqkff5jt2g5x0l7ns6w', max_length=30),
        ),
    ]
