# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-20 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0003_auto_20170918_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='healthier_ID',
            field=models.CharField(default='consumer_s9z979nuxbkpbmu4qs6g', max_length=30),
        ),
    ]
