# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-26 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0004_auto_20170926_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='healthier_id',
            field=models.CharField(default='consumer_8xli736lkri8z5pca7bs', max_length=30),
        ),
    ]
