# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-24 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0004_auto_20170924_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='healthier_id',
            field=models.CharField(default='consumer_xjfdimrfa0eswzz7wdq2', max_length=30),
        ),
    ]
