# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-24 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0007_auto_20170924_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='healthier_id',
            field=models.CharField(default='consumer_yj6oojb50dnxerij56g9', max_length=30),
        ),
    ]
