# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-24 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0011_auto_20170924_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='healthier_id',
            field=models.CharField(default='consumer_l9b8rzhrpex2t1fqddle', max_length=30),
        ),
    ]
