# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-26 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthieruser',
            name='has_configure_account',
            field=models.BooleanField(default=True, verbose_name='Superuser'),
        ),
    ]
