# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-26 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_healthieruser_has_configure_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthieruser',
            name='has_configure_account',
            field=models.BooleanField(default=False, verbose_name='Has Configured Account'),
        ),
    ]
